### ISSUE TITLE
met some errors

### ISSUE THREAD

**Issue by Kgg-moon** [T1esh0u/SecScanC2#2]
I run a admin in my ecs,and a node in my pc,and it throw thw erros as follows:

Failed connecting to  12D3KooWG4vmGkWw2dWt98mjwjfpfYey7QYdwx1NwhMSCrUXo8Uo , error: failed to dial: failed to dial 12D3KooWG4vmGkWw2dWt98mjwjfpfYey7QYdwx1NwhMSCrUXo8Uo:
  * [/ip4/127.0.0.1/tcp/36515] dial tcp4 127.0.0.1:36515: connect: connection refused
  * [/ip4/10.0.12.2/tcp/36515] dial tcp4 10.0.12.2:36515: connect: connection refused
  * [/ip4/x.x.x.x/tcp/36515] dial tcp4 0.0.0.0:41231->x.x.x.x:36515: i/o timeout

**Comment by T1esh0u** [comment]
> I run a admin in my ecs,and a node in my pc,and it throw thw erros as follows:
> 
> Failed connecting to 12D3KooWG4vmGkWw2dWt98mjwjfpfYey7QYdwx1NwhMSCrUXo8Uo , error: failed to dial: failed to dial 12D3KooWG4vmGkWw2dWt98mjwjfpfYey7QYdwx1NwhMSCrUXo8Uo:
> 
> * [/ip4/127.0.0.1/tcp/36515] dial tcp4 127.0.0.1:36515: connect: connection refused
> * [/ip4/10.0.12.2/tcp/36515] dial tcp4 10.0.12.2:36515: connect: connection refused
> * [/ip4/x.x.x.x/tcp/36515] dial tcp4 0.0.0.0:41231->x.x.x.x:36515: i/o timeout

Does your pc have an internet address? Please ensure network connectivity between your ecs and pc. You can try using telnet to see if they can connect with each other.

**Comment by Kgg-moon** [comment]
> > I run a admin in my ecs,and a node in my pc,and it throw thw erros as follows:
> > Failed connecting to 12D3KooWG4vmGkWw2dWt98mjwjfpfYey7QYdwx1NwhMSCrUXo8Uo , error: failed to dial: failed to dial 12D3KooWG4vmGkWw2dWt98mjwjfpfYey7QYdwx1NwhMSCrUXo8Uo:
> > 
> > * [/ip4/127.0.0.1/tcp/36515] dial tcp4 127.0.0.1:36515: connect: connection refused
> > * [/ip4/10.0.12.2/tcp/36515] dial tcp4 10.0.12.2:36515: connect: connection refused
> > * [/ip4/x.x.x.x/tcp/36515] dial tcp4 0.0.0.0:41231->x.x.x.x:36515: i/o timeout
> 
> Does your pc have an internet address? Please ensure network connectivity between your ecs and pc. You can try using telnet to see if they can connect with each other.

I have used telnet to confirm that my ecs is communicating with my pc

**Comment by T1esh0u** [comment]
> > > I run a admin in my ecs,and a node in my pc,and it throw thw erros as follows:
> > > Failed connecting to 12D3KooWG4vmGkWw2dWt98mjwjfpfYey7QYdwx1NwhMSCrUXo8Uo , error: failed to dial: failed to dial 12D3KooWG4vmGkWw2dWt98mjwjfpfYey7QYdwx1NwhMSCrUXo8Uo:
> > > 
> > > * [/ip4/127.0.0.1/tcp/36515] dial tcp4 127.0.0.1:36515: connect: connection refused
> > > * [/ip4/10.0.12.2/tcp/36515] dial tcp4 10.0.12.2:36515: connect: connection refused
> > > * [/ip4/x.x.x.x/tcp/36515] dial tcp4 0.0.0.0:41231->x.x.x.x:36515: i/o timeout
> > 
> > 
> > Does your pc have an internet address? Please ensure network connectivity between your ecs and pc. You can try using telnet to see if they can connect with each other.
> 
> I have used telnet to confirm that my ecs is communicating with my pc

Have you tried both directions? Can they sucessfully telnet with each other? Can your ecs connect to the port of your pc?

**Comment by Kgg-moon** [comment]
> > > > I run a admin in my ecs,and a node in my pc,and it throw thw erros as follows:
> > > > Failed connecting to 12D3KooWG4vmGkWw2dWt98mjwjfpfYey7QYdwx1NwhMSCrUXo8Uo , error: failed to dial: failed to dial 12D3KooWG4vmGkWw2dWt98mjwjfpfYey7QYdwx1NwhMSCrUXo8Uo:
> > > > 
> > > > * [/ip4/127.0.0.1/tcp/36515] dial tcp4 127.0.0.1:36515: connect: connection refused
> > > > * [/ip4/10.0.12.2/tcp/36515] dial tcp4 10.0.12.2:36515: connect: connection refused
> > > > * [/ip4/x.x.x.x/tcp/36515] dial tcp4 0.0.0.0:41231->x.x.x.x:36515: i/o timeout
> > > 
> > > 
> > > Does your pc have an internet address? Please ensure network connectivity between your ecs and pc. You can try using telnet to see if they can connect with each other.
> > 
> > 
> > I have used telnet to confirm that my ecs is communicating with my pc
> 
> Have you tried both directions? Can they sucessfully telnet with each other? Can your ecs connect to the port of your pc?

It is indeed my problem. When I use two ECS, it works fine
